/*
  File autogenerated by gengetopt version 2.22.6
  generated with the following command:
  gengetopt -i dv.ggo -F dv_cmdline 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "dv_cmdline.h"

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: " CMDLINE_PARSER_PACKAGE " [OPTIONS]...";

const char *gengetopt_args_info_versiontext = "";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                    Print help and exit",
  "  -V, --version                 Print version and exit",
  "\nServer",
  "  -H, --hostname=STRING         host name or IP address",
  "  -S, --simulator-port=portnumber\n                                simulator port",
  "  -C, --client-port=portnumber  client port",
  "  -F, --conf-file=STRING        configuration file",
  "\nPaths",
  "  -s, --simulator=STRING        simulator configuration path",
  "  -c, --checkpoints=STRING      checkpoint/restart files path",
  "  -r, --results=STRING          result files path",
  "  -d, --dummy=STRING            temporary redirect dummy path",
  "\nFile cache (unlimited, LRU, ARC, LIRS BCL, DCL, PLRU, PBCL, PDCL)",
  "  -t, --filecache-type=STRING   cache type",
  "  -n, --filecache-size=LONG     cache size",
  "  -f, --filecache-fifo-size=LONG\n                                size of the fifo queue (default 0)",
  "  -l, --filecache-lir-set-size=LONG\n                                LIR set size for LIRS",
  "  -m, --filecache-mrus=LONG     reserved MRUs",
  "  -p, --filecache-penalty=DOUBLE\n                                penalty factor",
  "\nPrefetching",
  "  -i, --prefetch-intervals=LONG max. number of intervals to be prefetched (sets\n                                  vertical to value and horizontal to 1)",
  "  -a, --horizontal-prefetch-interval=LONG\n                                max. number of intervals to be prefetched in\n                                  one simulation (horizontal)",
  "  -b, --vertical-prefetch-interval=LONG\n                                max. number of intervals to be prefetched by\n                                  multiple simulations (vertical)",
  "  -x, --parallel-simulators=LONG\n                                max. number of simulators running in parallel",
  "  -k, --sim-kill-threshold=LONG threshold for stopping a running simulator",
  "\n",
    0
};

typedef enum {ARG_NO
  , ARG_STRING
  , ARG_LONG
  , ARG_DOUBLE
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);


static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->hostname_given = 0 ;
  args_info->simulator_port_given = 0 ;
  args_info->client_port_given = 0 ;
  args_info->conf_file_given = 0 ;
  args_info->simulator_given = 0 ;
  args_info->checkpoints_given = 0 ;
  args_info->results_given = 0 ;
  args_info->dummy_given = 0 ;
  args_info->filecache_type_given = 0 ;
  args_info->filecache_size_given = 0 ;
  args_info->filecache_fifo_size_given = 0 ;
  args_info->filecache_lir_set_size_given = 0 ;
  args_info->filecache_mrus_given = 0 ;
  args_info->filecache_penalty_given = 0 ;
  args_info->prefetch_intervals_given = 0 ;
  args_info->horizontal_prefetch_interval_given = 0 ;
  args_info->vertical_prefetch_interval_given = 0 ;
  args_info->parallel_simulators_given = 0 ;
  args_info->sim_kill_threshold_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->hostname_arg = NULL;
  args_info->hostname_orig = NULL;
  args_info->simulator_port_arg = NULL;
  args_info->simulator_port_orig = NULL;
  args_info->client_port_arg = NULL;
  args_info->client_port_orig = NULL;
  args_info->conf_file_arg = NULL;
  args_info->conf_file_orig = NULL;
  args_info->simulator_arg = NULL;
  args_info->simulator_orig = NULL;
  args_info->checkpoints_arg = NULL;
  args_info->checkpoints_orig = NULL;
  args_info->results_arg = NULL;
  args_info->results_orig = NULL;
  args_info->dummy_arg = NULL;
  args_info->dummy_orig = NULL;
  args_info->filecache_type_arg = NULL;
  args_info->filecache_type_orig = NULL;
  args_info->filecache_size_orig = NULL;
  args_info->filecache_fifo_size_orig = NULL;
  args_info->filecache_lir_set_size_orig = NULL;
  args_info->filecache_mrus_orig = NULL;
  args_info->filecache_penalty_orig = NULL;
  args_info->prefetch_intervals_orig = NULL;
  args_info->horizontal_prefetch_interval_orig = NULL;
  args_info->vertical_prefetch_interval_orig = NULL;
  args_info->parallel_simulators_orig = NULL;
  args_info->sim_kill_threshold_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->hostname_help = gengetopt_args_info_help[3] ;
  args_info->simulator_port_help = gengetopt_args_info_help[4] ;
  args_info->client_port_help = gengetopt_args_info_help[5] ;
  args_info->conf_file_help = gengetopt_args_info_help[6] ;
  args_info->simulator_help = gengetopt_args_info_help[8] ;
  args_info->checkpoints_help = gengetopt_args_info_help[9] ;
  args_info->results_help = gengetopt_args_info_help[10] ;
  args_info->dummy_help = gengetopt_args_info_help[11] ;
  args_info->filecache_type_help = gengetopt_args_info_help[13] ;
  args_info->filecache_size_help = gengetopt_args_info_help[14] ;
  args_info->filecache_fifo_size_help = gengetopt_args_info_help[15] ;
  args_info->filecache_lir_set_size_help = gengetopt_args_info_help[16] ;
  args_info->filecache_mrus_help = gengetopt_args_info_help[17] ;
  args_info->filecache_penalty_help = gengetopt_args_info_help[18] ;
  args_info->prefetch_intervals_help = gengetopt_args_info_help[20] ;
  args_info->horizontal_prefetch_interval_help = gengetopt_args_info_help[21] ;
  args_info->vertical_prefetch_interval_help = gengetopt_args_info_help[22] ;
  args_info->parallel_simulators_help = gengetopt_args_info_help[23] ;
  args_info->sim_kill_threshold_help = gengetopt_args_info_help[24] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{

  free_string_field (&(args_info->hostname_arg));
  free_string_field (&(args_info->hostname_orig));
  free_string_field (&(args_info->simulator_port_arg));
  free_string_field (&(args_info->simulator_port_orig));
  free_string_field (&(args_info->client_port_arg));
  free_string_field (&(args_info->client_port_orig));
  free_string_field (&(args_info->conf_file_arg));
  free_string_field (&(args_info->conf_file_orig));
  free_string_field (&(args_info->simulator_arg));
  free_string_field (&(args_info->simulator_orig));
  free_string_field (&(args_info->checkpoints_arg));
  free_string_field (&(args_info->checkpoints_orig));
  free_string_field (&(args_info->results_arg));
  free_string_field (&(args_info->results_orig));
  free_string_field (&(args_info->dummy_arg));
  free_string_field (&(args_info->dummy_orig));
  free_string_field (&(args_info->filecache_type_arg));
  free_string_field (&(args_info->filecache_type_orig));
  free_string_field (&(args_info->filecache_size_orig));
  free_string_field (&(args_info->filecache_fifo_size_orig));
  free_string_field (&(args_info->filecache_lir_set_size_orig));
  free_string_field (&(args_info->filecache_mrus_orig));
  free_string_field (&(args_info->filecache_penalty_orig));
  free_string_field (&(args_info->prefetch_intervals_orig));
  free_string_field (&(args_info->horizontal_prefetch_interval_orig));
  free_string_field (&(args_info->vertical_prefetch_interval_orig));
  free_string_field (&(args_info->parallel_simulators_orig));
  free_string_field (&(args_info->sim_kill_threshold_orig));
  
  

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->hostname_given)
    write_into_file(outfile, "hostname", args_info->hostname_orig, 0);
  if (args_info->simulator_port_given)
    write_into_file(outfile, "simulator-port", args_info->simulator_port_orig, 0);
  if (args_info->client_port_given)
    write_into_file(outfile, "client-port", args_info->client_port_orig, 0);
  if (args_info->conf_file_given)
    write_into_file(outfile, "conf-file", args_info->conf_file_orig, 0);
  if (args_info->simulator_given)
    write_into_file(outfile, "simulator", args_info->simulator_orig, 0);
  if (args_info->checkpoints_given)
    write_into_file(outfile, "checkpoints", args_info->checkpoints_orig, 0);
  if (args_info->results_given)
    write_into_file(outfile, "results", args_info->results_orig, 0);
  if (args_info->dummy_given)
    write_into_file(outfile, "dummy", args_info->dummy_orig, 0);
  if (args_info->filecache_type_given)
    write_into_file(outfile, "filecache-type", args_info->filecache_type_orig, 0);
  if (args_info->filecache_size_given)
    write_into_file(outfile, "filecache-size", args_info->filecache_size_orig, 0);
  if (args_info->filecache_fifo_size_given)
    write_into_file(outfile, "filecache-fifo-size", args_info->filecache_fifo_size_orig, 0);
  if (args_info->filecache_lir_set_size_given)
    write_into_file(outfile, "filecache-lir-set-size", args_info->filecache_lir_set_size_orig, 0);
  if (args_info->filecache_mrus_given)
    write_into_file(outfile, "filecache-mrus", args_info->filecache_mrus_orig, 0);
  if (args_info->filecache_penalty_given)
    write_into_file(outfile, "filecache-penalty", args_info->filecache_penalty_orig, 0);
  if (args_info->prefetch_intervals_given)
    write_into_file(outfile, "prefetch-intervals", args_info->prefetch_intervals_orig, 0);
  if (args_info->horizontal_prefetch_interval_given)
    write_into_file(outfile, "horizontal-prefetch-interval", args_info->horizontal_prefetch_interval_orig, 0);
  if (args_info->vertical_prefetch_interval_given)
    write_into_file(outfile, "vertical-prefetch-interval", args_info->vertical_prefetch_interval_orig, 0);
  if (args_info->parallel_simulators_given)
    write_into_file(outfile, "parallel-simulators", args_info->parallel_simulators_orig, 0);
  if (args_info->sim_kill_threshold_given)
    write_into_file(outfile, "sim-kill-threshold", args_info->sim_kill_threshold_orig, 0);
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  FIX_UNUSED (args_info);
  FIX_UNUSED (prog_name);
  return EXIT_SUCCESS;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_LONG:
    if (val) *((long *)field) = (long)strtol (val, &stop_char, 0);
    break;
  case ARG_DOUBLE:
    if (val) *((double *)field) = strtod (val, &stop_char);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_LONG:
  case ARG_DOUBLE:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "hostname",	1, NULL, 'H' },
        { "simulator-port",	1, NULL, 'S' },
        { "client-port",	1, NULL, 'C' },
        { "conf-file",	1, NULL, 'F' },
        { "simulator",	1, NULL, 's' },
        { "checkpoints",	1, NULL, 'c' },
        { "results",	1, NULL, 'r' },
        { "dummy",	1, NULL, 'd' },
        { "filecache-type",	1, NULL, 't' },
        { "filecache-size",	1, NULL, 'n' },
        { "filecache-fifo-size",	1, NULL, 'f' },
        { "filecache-lir-set-size",	1, NULL, 'l' },
        { "filecache-mrus",	1, NULL, 'm' },
        { "filecache-penalty",	1, NULL, 'p' },
        { "prefetch-intervals",	1, NULL, 'i' },
        { "horizontal-prefetch-interval",	1, NULL, 'a' },
        { "vertical-prefetch-interval",	1, NULL, 'b' },
        { "parallel-simulators",	1, NULL, 'x' },
        { "sim-kill-threshold",	1, NULL, 'k' },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVH:S:C:F:s:c:r:d:t:n:f:l:m:p:i:a:b:x:k:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'H':	/* host name or IP address.  */
        
        
          if (update_arg( (void *)&(args_info->hostname_arg), 
               &(args_info->hostname_orig), &(args_info->hostname_given),
              &(local_args_info.hostname_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "hostname", 'H',
              additional_error))
            goto failure;
        
          break;
        case 'S':	/* simulator port.  */
        
        
          if (update_arg( (void *)&(args_info->simulator_port_arg), 
               &(args_info->simulator_port_orig), &(args_info->simulator_port_given),
              &(local_args_info.simulator_port_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "simulator-port", 'S',
              additional_error))
            goto failure;
        
          break;
        case 'C':	/* client port.  */
        
        
          if (update_arg( (void *)&(args_info->client_port_arg), 
               &(args_info->client_port_orig), &(args_info->client_port_given),
              &(local_args_info.client_port_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "client-port", 'C',
              additional_error))
            goto failure;
        
          break;
        case 'F':	/* configuration file.  */
        
        
          if (update_arg( (void *)&(args_info->conf_file_arg), 
               &(args_info->conf_file_orig), &(args_info->conf_file_given),
              &(local_args_info.conf_file_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "conf-file", 'F',
              additional_error))
            goto failure;
        
          break;
        case 's':	/* simulator configuration path.  */
        
        
          if (update_arg( (void *)&(args_info->simulator_arg), 
               &(args_info->simulator_orig), &(args_info->simulator_given),
              &(local_args_info.simulator_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "simulator", 's',
              additional_error))
            goto failure;
        
          break;
        case 'c':	/* checkpoint/restart files path.  */
        
        
          if (update_arg( (void *)&(args_info->checkpoints_arg), 
               &(args_info->checkpoints_orig), &(args_info->checkpoints_given),
              &(local_args_info.checkpoints_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "checkpoints", 'c',
              additional_error))
            goto failure;
        
          break;
        case 'r':	/* result files path.  */
        
        
          if (update_arg( (void *)&(args_info->results_arg), 
               &(args_info->results_orig), &(args_info->results_given),
              &(local_args_info.results_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "results", 'r',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* temporary redirect dummy path.  */
        
        
          if (update_arg( (void *)&(args_info->dummy_arg), 
               &(args_info->dummy_orig), &(args_info->dummy_given),
              &(local_args_info.dummy_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "dummy", 'd',
              additional_error))
            goto failure;
        
          break;
        case 't':	/* cache type.  */
        
        
          if (update_arg( (void *)&(args_info->filecache_type_arg), 
               &(args_info->filecache_type_orig), &(args_info->filecache_type_given),
              &(local_args_info.filecache_type_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "filecache-type", 't',
              additional_error))
            goto failure;
        
          break;
        case 'n':	/* cache size.  */
        
        
          if (update_arg( (void *)&(args_info->filecache_size_arg), 
               &(args_info->filecache_size_orig), &(args_info->filecache_size_given),
              &(local_args_info.filecache_size_given), optarg, 0, 0, ARG_LONG,
              check_ambiguity, override, 0, 0,
              "filecache-size", 'n',
              additional_error))
            goto failure;
        
          break;
        case 'f':	/* size of the fifo queue (default 0).  */
        
        
          if (update_arg( (void *)&(args_info->filecache_fifo_size_arg), 
               &(args_info->filecache_fifo_size_orig), &(args_info->filecache_fifo_size_given),
              &(local_args_info.filecache_fifo_size_given), optarg, 0, 0, ARG_LONG,
              check_ambiguity, override, 0, 0,
              "filecache-fifo-size", 'f',
              additional_error))
            goto failure;
        
          break;
        case 'l':	/* LIR set size for LIRS.  */
        
        
          if (update_arg( (void *)&(args_info->filecache_lir_set_size_arg), 
               &(args_info->filecache_lir_set_size_orig), &(args_info->filecache_lir_set_size_given),
              &(local_args_info.filecache_lir_set_size_given), optarg, 0, 0, ARG_LONG,
              check_ambiguity, override, 0, 0,
              "filecache-lir-set-size", 'l',
              additional_error))
            goto failure;
        
          break;
        case 'm':	/* reserved MRUs.  */
        
        
          if (update_arg( (void *)&(args_info->filecache_mrus_arg), 
               &(args_info->filecache_mrus_orig), &(args_info->filecache_mrus_given),
              &(local_args_info.filecache_mrus_given), optarg, 0, 0, ARG_LONG,
              check_ambiguity, override, 0, 0,
              "filecache-mrus", 'm',
              additional_error))
            goto failure;
        
          break;
        case 'p':	/* penalty factor.  */
        
        
          if (update_arg( (void *)&(args_info->filecache_penalty_arg), 
               &(args_info->filecache_penalty_orig), &(args_info->filecache_penalty_given),
              &(local_args_info.filecache_penalty_given), optarg, 0, 0, ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "filecache-penalty", 'p',
              additional_error))
            goto failure;
        
          break;
        case 'i':	/* max. number of intervals to be prefetched (sets vertical to value and horizontal to 1).  */
        
        
          if (update_arg( (void *)&(args_info->prefetch_intervals_arg), 
               &(args_info->prefetch_intervals_orig), &(args_info->prefetch_intervals_given),
              &(local_args_info.prefetch_intervals_given), optarg, 0, 0, ARG_LONG,
              check_ambiguity, override, 0, 0,
              "prefetch-intervals", 'i',
              additional_error))
            goto failure;
        
          break;
        case 'a':	/* max. number of intervals to be prefetched in one simulation (horizontal).  */
        
        
          if (update_arg( (void *)&(args_info->horizontal_prefetch_interval_arg), 
               &(args_info->horizontal_prefetch_interval_orig), &(args_info->horizontal_prefetch_interval_given),
              &(local_args_info.horizontal_prefetch_interval_given), optarg, 0, 0, ARG_LONG,
              check_ambiguity, override, 0, 0,
              "horizontal-prefetch-interval", 'a',
              additional_error))
            goto failure;
        
          break;
        case 'b':	/* max. number of intervals to be prefetched by multiple simulations (vertical).  */
        
        
          if (update_arg( (void *)&(args_info->vertical_prefetch_interval_arg), 
               &(args_info->vertical_prefetch_interval_orig), &(args_info->vertical_prefetch_interval_given),
              &(local_args_info.vertical_prefetch_interval_given), optarg, 0, 0, ARG_LONG,
              check_ambiguity, override, 0, 0,
              "vertical-prefetch-interval", 'b',
              additional_error))
            goto failure;
        
          break;
        case 'x':	/* max. number of simulators running in parallel.  */
        
        
          if (update_arg( (void *)&(args_info->parallel_simulators_arg), 
               &(args_info->parallel_simulators_orig), &(args_info->parallel_simulators_given),
              &(local_args_info.parallel_simulators_given), optarg, 0, 0, ARG_LONG,
              check_ambiguity, override, 0, 0,
              "parallel-simulators", 'x',
              additional_error))
            goto failure;
        
          break;
        case 'k':	/* threshold for stopping a running simulator.  */
        
        
          if (update_arg( (void *)&(args_info->sim_kill_threshold_arg), 
               &(args_info->sim_kill_threshold_orig), &(args_info->sim_kill_threshold_given),
              &(local_args_info.sim_kill_threshold_given), optarg, 0, 0, ARG_LONG,
              check_ambiguity, override, 0, 0,
              "sim-kill-threshold", 'k',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */




  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
